### ISSUE TITLE
Swift 6  -> errors

### ISSUE THREAD

**Issue by stodevCoding** [Mijick/Popups#111]
`Main actor-isolated instance method 'createContent()' cannot be used to satisfy nonisolated protocol requirement`
`Main actor-isolated instance method 'configurePopup(popup:)' cannot be used to satisfy nonisolated protocol requirement`

Hi there, 
Here's an update after Swift 6 was made available, with a lot of upgrades to do, good luck ;)

Thanks for your libs

**Comment by FulcrumOne** [comment]
Hey @stodevCoding,

Thank you very much for this finding - I haven't downloaded Xcode Beta yet, so this is very helpful 😉
We will include this fix in the sprint we are planning for the end of this month.

Thanks for using our libraries and have a great day,
T.K.
