### ISSUE TITLE
default background

### ISSUE THREAD

**Issue by LuegM** [Mijick/Popups#134]
Could you please set the default background to:

`.backgroundColour(Color(UIColor.tertiarySystemBackground)'`

so that the popups also look good in dark mode from the beginning?

**Comment by FulcrumOne** [comment]
Hey @LuegM,

You can easily set the default background for all popups using the code below:
![CleanShot 2024-10-28 at 11 15 15](https://github.com/user-attachments/assets/73a68305-00cd-4de1-b9ee-d7012e61d85b)

Have a nice day,
Tomasz
