### ISSUE TITLE
Popup position shifts after enabling .tapOutsideToDismiss(true) and dismissing by tapping outside

### ISSUE THREAD

**Issue by El549** [Mijick/Popups#141]
**Description**:

I'm using the PopupView framework and have encountered an issue when I enable `.tapOutsideToDismiss(true)` to allow dismissing the popup by tapping outside. The specific problem is:

- After triggering the popup for the first time and dismissing it by tapping outside, it seems that the gesture detection remains active.
- When I trigger the popup again, the initial position of the popup shifts and does not appear at the expected location.

**Steps to Reproduce**:

1. Configure PopupView with `.tapOutsideToDismiss(true)` enabled.
2. Trigger the popup to display.
3. Dismiss the popup by tapping outside.
4. Trigger the popup again.

**Expected Behavior**:

- The popup should appear at the same initial position every time it is displayed.

**Actual Behavior**:

- On the second and subsequent displays, the popup's position is shifted and not at the original expected location.

**Possible Cause**:

- After dismissing the popup, the gesture detection is not properly removed, causing incorrect position calculations the next time the popup is displayed.

**Additional Information**:

- I can provide relevant code snippets or a demo video if needed.

I hope the developers can look into this issue. Thank you very much!

**Comment by FulcrumOne** [comment]
Hey @El549,

The problem should be fixed in the newest framework version.

Have a nice day,
Tomasz
