### ISSUE TITLE
[BUG] Still Crashes on 4.0.0 pre iOS 17

### ISSUE THREAD

**Issue by bukira** [Mijick/Popups#162]
Updated to 3.0.0 and 4.0.0 and the popup still crashes for iOS 16 and below

iOS 17 and iOS 18 work fine

```
// MARK: Popup Height
extension ViewModel {
    func updatePopupHeight(_ heightCandidate: CGFloat, _ popup: AnyPopup) async {
        guard activePopupProperties.gestureTranslation == 0 else { return }

        let newHeight = await calculatePopupHeight(heightCandidate, popup)
        if newHeight != popup.height {
            await updatePopupAction(popup.updatedHeight(newHeight))
        }
    }
}
```

Thread 1: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

crashes on the line:
**await updatePopupAction(popup.updatedHeight(newHeight))**

for centre and bottom popups 

Printing description of newHeight:
0.0
Printing description of heightCandidate:
319.0
Printing description of popup.height:
nil

Same popus didnt crash pre 3.0.0

**Comment by FulcrumOne** [comment]
Hey @bukira,

Thanks for letting me know. Could you please show me the part of the code where you call the `.registerPopups()` method, as a similar issue was recently created (#158) and I wonder if this is somehow related. 

Thanks again for your help,
Tomasz

**Comment by bukira** [comment]
Yes certainly


```
 var body: some Scene {
        WindowGroup {
            RootView()
                .registerPopups()
                .logRender("RootView")
        }
        .onChange(of: phase) { newPhase in
            switch newPhase {
            case .active:
                activePhase() //App became active
            case .inactive:
                inactivePhase() //App became inactive
            case .background:
                backgroundPhase() //App is running in the background no UI
            @unknown default: break
                //Fallback for future cases
            }
        }
    }
```

@main
struct App: App {
    
    @Environment(\.scenePhase) private var phase
    
    @UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate
    
    init() {
        setupFirebase()
        setupConfig()
        setupDependencies()
        setupAppearance()
        setupPageControl()
    }
    
    var body: some Scene {
        WindowGroup {
            RootView()
                .registerPopups()
                .logRender("RootView")
        }
        .onChange(of: phase) { newPhase in
            switch newPhase {
            case .active:
                activePhase() //App became active
            case .inactive:
                inactivePhase() //App became inactive
            case .background:
                backgroundPhase() //App is running in the background no UI
            @unknown default: break
                //Fallback for future cases
            }
        }
    }
}

**Comment by FulcrumOne** [comment]
@bukira, could you, for testing purposes comment out ``@Environment(`.scenePhase) private var phase`` and see if the crash still occurs? If so, I think I know how I can fix it

**Comment by bukira** [comment]
doesnt crash with that commented out

**Comment by FulcrumOne** [comment]
Great. I mean not great, but at least I know how to fix it. I will provide you with a solution in a moment.

**Comment by FulcrumOne** [comment]
Could you check if the `patch-4.0.1` branch solves your problem?

**Comment by FulcrumOne** [comment]
Haha, glad to hear that. Unfortunately, I'll have to do some additional testing before this goes public, as there were reasons why I wanted to avoid such a solution 😅

Have a nice day @bukira!

**Comment by wwzzyying** [comment]
<img width="1344" alt="image" src="https://github.com/user-attachments/assets/e3b4c90f-b500-491d-90de-d819cdcbbcca">

Hi FulcrumOne, I also got this crash with iOS17, my registerPopups just like this.

<img width="727" alt="image" src="https://github.com/user-attachments/assets/47cc5558-85f5-46ca-a66d-3a446ce88202">

**Comment by kevinobssuth** [comment]
hey man. I am finding that first crash from the first comment on here on iOS 18

**Comment by Vincz** [comment]
I do have the same issue at the same line on macOS. 
I'm trying to attach the `.registerPopups` to a view (note that I don't use `Scene` my windows are created manually and View injected through `NSHostingView`).

**Comment by FulcrumOne** [comment]
Did you try the branch patch-4.0.1?

**Comment by Vincz** [comment]
> Did you try the branch patch-4.0.1?

Just tried. It works perfectly 😄
