### ISSUE TITLE
[BUG] The problem of Apple form overlay Sheet reappears in iOS 18.1

### ISSUE THREAD

**Issue by ByLiangCheng** [Mijick/Popups#164]
As the title says, I've seen this issues: https://github.com/Mijick/Popups/issues/110

It is normal to try in IOS15 by referring to the issues code, but the view will pop up in IOS18. After it pops up, the entire interface can no longer be clicked.

The version of Popups library is 2.7.1

@FulcrumOne

**Comment by FulcrumOne** [comment]
Hey @ByLiangCheng,

This problem was related to the fact that Apple has broken hit tests on the newest iOS. However, I made a fix for this issue, which is deployed on the version 3.0.0 (I would suggest you to use the newest version, which is 4.0.0).

Thanks,
Tomasz

**Comment by ByLiangCheng** [comment]
May I ask if version 2.x.x is no longer maintained? Because I'm still using 2.7.1 library syntax.

I'm a little concerned because I see that the 4.x.x version was released not long ago, and I'm not sure if there will be hidden unknown issues after immediately migrating to the 4.x.x version, and how long it will take to make the changes

Finally, thank you for your response and for contributing to it

**Comment by FulcrumOne** [comment]
Hey @ByLiangCheng,

No, unfortunately we only support the latest version. However, it should be stable; I wouldn't expect any major issues here.

Have a nice day,
Tomasz K.
